name: Find Special Hash CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  run-hash-finder:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run hash finder script
        run: python hash.py
